CREATE OR REPLACE FUNCTION SHIFT_MONEY(ID IN VARCHAR2, SRC IN NUMBER, AMOUNT IN NUMBER)
RETURN VARCHAR2 IS
	SRCAMOUNT NUMBER;
	CHECKSHIFT VARCHAR2(1);
BEGIN
	SELECT "Amount" INTO SRCAMOUNT
	FROM "FINANCEMANAGER"."FinancialInfo"
	WHERE "UserID" = ID
	AND "WalletID" = SRC;
	
	IF SRCAMOUNT >= AMOUNT THEN 
		CHECKSHIFT := 'T';
	ELSIF SRCAMOUNT < AMOUNT THEN
		CHECKSHIFT := 'F';
	END IF;
	RETURN CHECKSHIFT;
END;

CREATE OR REPLACE FUNCTION VERIFY_LOGIN(MAIL IN VARCHAR2, PASS IN VARCHAR2)
RETURN VARCHAR2 IS
	CNT NUMBER;
	CHECKLOGIN VARCHAR2(1);
BEGIN
	SELECT COUNT(*) INTO CNT
  FROM "FINANCEMANAGER"."AccountInfo"
  WHERE "Mail" = MAIL
  AND "Password" = PASS;
	
	IF CNT > 0 THEN 
		CHECKLOGIN := 'T';
	ELSIF CNT = 0 THEN
		CHECKLOGIN := 'F';
	END IF;
	RETURN CHECKLOGIN;
END;