CREATE OR REPLACE TRIGGER CHECK_EDIT_BUDGET_INFO
BEFORE UPDATE
OF "Amount"
ON "Budgets"
FOR EACH ROW
DECLARE 
BEGIN
	IF :NEW."Amount" = 0 THEN
		:NEW."Amount" = :OLD."Amount";	
	END IF;
END;
/

--Edit Budget
--Delete Wallet/ Account
--Transaction validity

CREATE TABLE LOG_DELETED_WALLET_TABLE
(
	UserID VARCHAR2(30),
	WalletID NUMBER,
	Shifted Money NUMBER
);

CREATE OR REPLACE TRIGGER LOG_DELETED_WALLET
BEFORE DELETE
ON "FINANCEMANAGER"."FinancialInfo"
DECLARE
BEGIN
	INSERT INTO LOG_DELETED_WALLET_TABLE VALUES (:OLD.UserID, :OLD.WalletID, :OLD.Amount);
END;
/

CREATE TABLE LOG_DELETED_ACCOUNT_TABLE
(
	UserID VARCHAR2(30),
	Mail VARCHAR2(100)
);

CREATE OR REPLACE TRIGGER LOG_DELETED_ACCOUNT
BEFORE DELETE
ON "FINANCEMANAGER"."AccountInfo"
DECLARE
BEGIN
	INSERT INTO LOG_DELETED_ACCOUNT_TABLE VALUES(:OLD.UserID, :OLD.Mail);
END;
/




