CREATE OR REPLACE PROCEDURE NEW_FINANCIAL_INFO(USERID IN VARCHAR2) IS
	COUNTPREVWALLETS NUMBER;
	NEWWALLETNUMBER NUMBER;
BEGIN
	SELECT "Wallets" INTO COUNTPREVWALLETS
	FROM "FINANCEMANAGER"."WalletsInfo"
	WHERE "UserID" LIKE USERID;
	
	NEWWALLETNUMBER := COUNTPREVWALLETS + 1;
	
	UPDATE "FINANCEMANAGER"."WalletsInfo"
  	SET "Wallets" = NEWWALLETNUMBER
  	WHERE "UserID" LIKE USERID;
					 
	INSERT INTO "FINANCEMANAGER"."FinancialInfo" VALUES (USERID, NEWWALLETNUMBER, 0.00, SYSDATE, SYSDATE);
END;
/



CREATE OR REPLACE PROCEDURE DELETE_WALLET_FROM_TABLES(USERID IN VARCHAR2, WALLETID IN NUMBER) IS
BEGIN
	UPDATE "FINANCEMANAGER"."WalletsInfo"
	SET "Wallets" = "Wallets" - 1
	WHERE "UserID" = USERID;
	
	DELETE FROM "FINANCEMANAGER"."FinancialInfo"
	WHERE "UserID" = USERID
	AND "WalletID" = WALLETID;
	
	DELETE FROM "FINANCEMANAGER"."Incomes"
	WHERE "UserID" = USERID
	AND "WalletID" = WALLETID;
	
	DELETE FROM "FINANCEMANAGER"."Expenses"
	WHERE "UserID" = USERID
	AND "WalletID" = WALLETID;
END;


CREATE OR REPLACE PROCEDURE UPDATE_TABLES_AFTER_DELETE_WALLET(USERID IN VARCHAR2, WALLETID IN NUMBER) IS
BEGIN
UPDATE "FINANCEMANAGER"."FinancialInfo"
	SET "WalletID" = "WalletID" - 1
	WHERE "WalletID" > WALLETID
	AND "UserID" LIKE USERID;
	
	UPDATE "FINANCEMANAGER"."Incomes"
	SET "WalletID" = "WalletID" - 1
	WHERE "WalletID" > WALLETID
	AND "UserID" LIKE USERID;
	
	UPDATE "FINANCEMANAGER"."Expenses"
	SET "WalletID" = "WalletID" - 1
	WHERE "WalletID" > WALLETID
	AND "UserID" LIKE USERID;
END;